name: erlab
channels:
  - conda-forge
dependencies:
  - ase>=3.17.0
  - asteval>=0.9.22
  - astropy
  - bokeh>=2.0.0
  - bottleneck>=1.3.2
  - colorama
  - colorcet
  - dill
  - h5py>=3.2.1
  - imageio
  - ipython
  - ipywidgets>=7.0.1
  - joblib
  - llvmlite
  - lmfit>=1.0.0
  - matplotlib>=3.5.0
  - netCDF4>=1.5.0
  - numba>=0.55.1
  - numpy>=1.20.0,<1.22.0
  - packaging
  - pandas
  - pint
  - pip>=19.3
  - pygments
  - pyqtgraph>=0.12.3
  - python=3.9
  - rx
  - scipy>=1.7.3
  - setuptools
  - tbb
  - titlecase
  - tqdm
  - uncertainties>=3.0.1
  - xarray>=0.16.1
  - scikit-learn>=0.24.0
  - pip:
    - pyside6>=6.2.2
    - -e git+https://github.com/kmnhan/erlabpy.git
    - -e git+https://github.com/kmnhan/igorpy.git
    - -e git+https://github.com/kmnhan/arpes.git
    - -e git+https://github.com/kmnhan/chinook.git
    - -e git+https://github.com/kmnhan/PyImageTool.git