name: erlab
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - ipython
  - pip>=19.3
  - setuptools
  - packaging
  - libblas=*=*accelerate
  - libcblas=*=*accelerate
  - liblapack=*=*accelerate
  - liblapacke=*=*accelerate
  - h5netcdf
  - varname
  - cmocean
  - cmasher
  - numpy=1.21.*
  - scipy>=1.7.3
  - matplotlib>=3.5.0
  - h5py>=3.2.1
  - netCDF4>=1.5.0
  - astropy
  - superqt>=0.3.1
  - dill
  - llvm-openmp>=13.0.0
  - llvmlite
  - asteval>=0.9.22
  - xarray>=0.16.1
  - numba>=0.55.1
  - ase>=3.17.0
  - bokeh>=2.0.0
  - bottleneck>=1.3.2
  - colorama
  - colorcet
  - imageio
  - ipywidgets>=7.0.1
  - joblib
  - lmfit>=1.0.0
  - pandas
  - pint
  - psutil
  - pygments
  - pyqtgraph>=0.12.3
  - rx
  - scikit-image
  - scikit-learn>=0.24.0
  - tbb
  - titlecase
  - tqdm
  - uncertainties>=3.0.1
  - qtawesome
  - pip:
    - pyside6>=6.2.2
    - numbagg
    - csaps
    - numba_progress
    - darkdetect
    - pyclip
    - -e git+https://github.com/kmnhan/erlabpy.git#egg=erlab
    - -e git+https://github.com/kmnhan/igorpy.git#egg=igor
    - -e git+https://github.com/kmnhan/arpes.git#egg=arpes
    - -e git+https://github.com/kmnhan/chinook.git#egg=chinook
    - -e git+https://github.com/kmnhan/PyImageTool.git#egg=pyimagetool